// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "HostId.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace rocketspeed { namespace djinni {

struct ConfigurationImpl final {

    std::vector<HostId> pilots;

    std::vector<HostId> copilots;

    int32_t tenant_id;


    ConfigurationImpl(
            std::vector<HostId> pilots,
            std::vector<HostId> copilots,
            int32_t tenant_id) :
                pilots(std::move(pilots)),
                copilots(std::move(copilots)),
                tenant_id(std::move(tenant_id)) {
    }
};

} }  // namespace rocketspeed::djinni
