// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "HostId.hpp"
#include <utility>
#include <vector>

namespace rocketspeed { namespace djinni {

struct ConfigurationImpl final {

    std::vector<HostId> pilots;

    std::vector<HostId> copilots;


    ConfigurationImpl(
            std::vector<HostId> pilots,
            std::vector<HostId> copilots) :
                pilots(std::move(pilots)),
                copilots(std::move(copilots)) {
    }
};

} }  // namespace rocketspeed::djinni
