// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "HostId.hpp"  // my header

namespace rocketspeed { namespace djinni {


bool HostId::operator==(const HostId & other) const {
    return hostname == other.hostname &&
        port == other.port;
}

bool HostId::operator!=(const HostId & other) const {
    return !(*this == other);
}

} }  // namespace rocketspeed::djinni
