// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace rocketspeed { namespace djinni {

struct MsgIdImpl final {

    static const int32_t SIZE;

    std::vector<uint8_t> guid;

    bool operator==(const MsgIdImpl & other) const;
    bool operator!=(const MsgIdImpl & other) const;

    MsgIdImpl(
            std::vector<uint8_t> guid) :
                guid(std::move(guid)) {
    }
};

} }  // namespace rocketspeed::djinni
