// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "MsgIdImpl.hpp"
#include "Status.hpp"
#include <cstdint>
#include <string>
#include <vector>

namespace rocketspeed { namespace djinni {

class PublishCallbackImpl {
public:
    virtual ~PublishCallbackImpl() {}

    virtual void Call(Status status, int32_t namespace_id, std::string topic_name, MsgIdImpl message_id, int64_t sequence_number, std::vector<uint8_t> contents) = 0;
};

} }  // namespace rocketspeed::djinni
