// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "MsgIdImpl.hpp"
#include "Status.hpp"
#include "optional.hpp"
#include <utility>

namespace rocketspeed { namespace djinni {

struct PublishStatus final {

    Status status;

    std::experimental::optional<MsgIdImpl> message_id;


    PublishStatus(
            Status status,
            std::experimental::optional<MsgIdImpl> message_id) :
                status(std::move(status)),
                message_id(std::move(message_id)) {
    }
};

} }  // namespace rocketspeed::djinni
