// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace rocketspeed { namespace djinni {

class ReceiveCallbackImpl {
public:
    virtual ~ReceiveCallbackImpl() {}

    virtual void Call(int32_t namespace_id, std::string topic_name, int64_t sequence_number, std::vector<uint8_t> contents) = 0;
};

} }  // namespace rocketspeed::djinni
