// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <functional>

namespace rocketspeed { namespace djinni {

enum class RetentionBase : int {
    ONEHOUR,
    ONEDAY,
    ONEWEEK,
};

} }  // namespace rocketspeed::djinni

namespace std {

template <>
struct hash<::rocketspeed::djinni::RetentionBase> {
    size_t operator()(::rocketspeed::djinni::RetentionBase type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
