// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <string>
#include <vector>

namespace rocketspeed { namespace djinni {

class DisconnectCallback {
public:
    virtual ~DisconnectCallback() {}

    virtual void Call(std::vector<std::string> client_ids) = 0;
};

} }  // namespace rocketspeed::djinni
