// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace rocketspeed { namespace djinni {

class DisconnectCallback {
public:
    virtual ~DisconnectCallback() {}

    virtual void Call(std::vector<int64_t> session_ids) = 0;
};

} }  // namespace rocketspeed::djinni
