// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace rocketspeed { namespace djinni {

struct HostId final {

    std::string hostname;

    int32_t port;

    bool operator==(const HostId & other) const;
    bool operator!=(const HostId & other) const;

    HostId(
            std::string hostname,
            int32_t port) :
                hostname(std::move(hostname)),
                port(std::move(port)) {
    }
};

} }  // namespace rocketspeed::djinni
