// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace rocketspeed { namespace djinni {

struct HostId final {
    std::string host;
    int32_t port;

    friend bool operator==(const HostId& lhs, const HostId& rhs);
    friend bool operator!=(const HostId& lhs, const HostId& rhs);

    HostId(std::string host,
           int32_t port)
    : host(std::move(host))
    , port(std::move(port))
    {}
};

} }  // namespace rocketspeed::djinni
