// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace rocketspeed { namespace djinni {

struct InboundID final {
    std::vector<uint8_t> serialised;

    friend bool operator==(const InboundID& lhs, const InboundID& rhs);
    friend bool operator!=(const InboundID& lhs, const InboundID& rhs);

    InboundID(std::vector<uint8_t> serialised)
    : serialised(std::move(serialised))
    {}
};

} }  // namespace rocketspeed::djinni
