// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/InboundID.hpp"  // my header

namespace rocketspeed { namespace djinni {


bool operator==(const InboundID& lhs, const InboundID& rhs) {
    return lhs.serialised == rhs.serialised;
}

bool operator!=(const InboundID& lhs, const InboundID& rhs) {
    return !(lhs == rhs);
}

} }  // namespace rocketspeed::djinni
