// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/MsgIdImpl.hpp"  // my header

namespace rocketspeed { namespace djinni {

const int32_t MsgIdImpl::SIZE = 16;

bool MsgIdImpl::operator==(const MsgIdImpl & other) const {
    return guid == other.guid;
}

bool MsgIdImpl::operator!=(const MsgIdImpl & other) const {
    return !(*this == other);
}

} }  // namespace rocketspeed::djinni
