// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/MsgId.hpp"  // my header

namespace rocketspeed { namespace djinni {


bool operator==(const MsgId& lhs, const MsgId& rhs) {
    return lhs.hi == rhs.hi &&
           lhs.lo == rhs.lo;
}

bool operator!=(const MsgId& lhs, const MsgId& rhs) {
    return !(lhs == rhs);
}

} }  // namespace rocketspeed::djinni
