// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace rocketspeed { namespace djinni {

struct MsgId final {
    int64_t hi;
    int64_t lo;

    friend bool operator==(const MsgId& lhs, const MsgId& rhs);
    friend bool operator!=(const MsgId& lhs, const MsgId& rhs);

    MsgId(int64_t hi,
          int64_t lo)
    : hi(std::move(hi))
    , lo(std::move(lo))
    {}
};

} }  // namespace rocketspeed::djinni
