// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/SubscriptionStorage.hpp"

namespace djinni_generated {

class NativeSubscriptionStorage final {
public:
    using CppType = ::rocketspeed::djinni::SubscriptionStorage;
    using JniType = jobject;

    using Boxed = NativeSubscriptionStorage;

    ~NativeSubscriptionStorage();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSubscriptionStorage();
    friend ::djinni::JniClass<NativeSubscriptionStorage>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/SubscriptionStorage") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lorg/rocketspeed/StorageType;Ljava/lang/String;)V") };
    const jfieldID field_type { ::djinni::jniGetFieldID(clazz.get(), "type", "Lorg/rocketspeed/StorageType;") };
    const jfieldID field_filePath { ::djinni::jniGetFieldID(clazz.get(), "filePath", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
