// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/Rocketeer.hpp"

namespace djinni_generated {

class NativeRocketeer final : ::djinni::JniInterface<::rocketspeed::djinni::Rocketeer, NativeRocketeer> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::Rocketeer>;
    using JniType = jobject;

    using Boxed = NativeRocketeer;

    ~NativeRocketeer();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRocketeer>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeRocketeer>::get()._toJava(jniEnv, c)}; }

private:
    NativeRocketeer();
    friend ::djinni::JniClass<NativeRocketeer>;
    friend ::djinni::JniInterface<::rocketspeed::djinni::Rocketeer, NativeRocketeer>;

    class JavaProxy final : ::djinni::JavaProxyCacheEntry, public ::rocketspeed::djinni::Rocketeer
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void HandleNewSubscription(::rocketspeed::djinni::InboundID inbound_id, ::rocketspeed::djinni::SubscriptionParameters params) override;
        void HandleTermination(::rocketspeed::djinni::InboundID inbound_id) override;

    private:
        using ::djinni::JavaProxyCacheEntry::getGlobalRef;
        friend ::djinni::JniInterface<::rocketspeed::djinni::Rocketeer, ::djinni_generated::NativeRocketeer>;
        friend ::djinni::JavaProxyCache<JavaProxy>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/Rocketeer") };
    const jmethodID method_handleNewSubscription { ::djinni::jniGetMethodID(clazz.get(), "handleNewSubscription", "(Lorg/rocketspeed/InboundID;Lorg/rocketspeed/SubscriptionParameters;)V") };
    const jmethodID method_handleTermination { ::djinni::jniGetMethodID(clazz.get(), "handleTermination", "(Lorg/rocketspeed/InboundID;)V") };
};

}  // namespace djinni_generated
