// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/RocketeerServerImpl.hpp"

namespace djinni_generated {

class NativeRocketeerServerImpl final : ::djinni::JniInterface<::rocketspeed::djinni::RocketeerServerImpl, NativeRocketeerServerImpl> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::RocketeerServerImpl>;
    using JniType = jobject;

    using Boxed = NativeRocketeerServerImpl;

    ~NativeRocketeerServerImpl();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRocketeerServerImpl>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeRocketeerServerImpl>::get()._toJava(jniEnv, c)}; }

private:
    NativeRocketeerServerImpl();
    friend ::djinni::JniClass<NativeRocketeerServerImpl>;
    friend ::djinni::JniInterface<::rocketspeed::djinni::RocketeerServerImpl, NativeRocketeerServerImpl>;

};

}  // namespace djinni_generated
