// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativeInboundID.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeInboundID::NativeInboundID() = default;

NativeInboundID::~NativeInboundID() = default;

auto NativeInboundID::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeInboundID>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::Binary::fromCpp(jniEnv, c.serialised).get())};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeInboundID::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeInboundID>::get();
    return {::djinni::Binary::toCpp(jniEnv, (jbyteArray)jniEnv->GetObjectField(j, data.field_serialised))};
}

}  // namespace djinni_generated
