// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativeHostId.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeHostId::NativeHostId() = default;

NativeHostId::~NativeHostId() = default;

auto NativeHostId::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHostId>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::String::fromCpp(jniEnv, c.host).get(),
                                                           ::djinni::I32::fromCpp(jniEnv, c.port))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHostId::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHostId>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_host)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_port))};
}

}  // namespace djinni_generated
