// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativeStatus.hpp"  // my header
#include "Marshal.hpp"
#include "src-gen/djinni/cpp/NativeStatusCode.hpp"

namespace djinni_generated {

NativeStatus::NativeStatus() = default;

NativeStatus::~NativeStatus() = default;

auto NativeStatus::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeStatus>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni_generated::NativeStatusCode::fromCpp(jniEnv, c.code).get(),
                                                           ::djinni::String::fromCpp(jniEnv, c.state).get())};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeStatus::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeStatus>::get();
    return {::djinni_generated::NativeStatusCode::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_code)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_state))};
}

}  // namespace djinni_generated
