// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/Status.hpp"

namespace djinni_generated {

class NativeStatus final {
public:
    using CppType = ::rocketspeed::djinni::Status;
    using JniType = jobject;

    using Boxed = NativeStatus;

    ~NativeStatus();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeStatus();
    friend ::djinni::JniClass<NativeStatus>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/Status") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lorg/rocketspeed/StatusCode;Ljava/lang/String;)V") };
    const jfieldID field_code { ::djinni::jniGetFieldID(clazz.get(), "code", "Lorg/rocketspeed/StatusCode;") };
    const jfieldID field_state { ::djinni::jniGetFieldID(clazz.get(), "state", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
