// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/SnapshotCallback.hpp"

namespace djinni_generated {

class NativeSnapshotCallback final : ::djinni::JniInterface<::rocketspeed::djinni::SnapshotCallback, NativeSnapshotCallback> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::SnapshotCallback>;
    using JniType = jobject;

    using Boxed = NativeSnapshotCallback;

    ~NativeSnapshotCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSnapshotCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeSnapshotCallback>::get()._toJava(jniEnv, c)}; }

private:
    NativeSnapshotCallback();
    friend ::djinni::JniClass<NativeSnapshotCallback>;
    friend ::djinni::JniInterface<::rocketspeed::djinni::SnapshotCallback, NativeSnapshotCallback>;

    class JavaProxy final : ::djinni::JavaProxyCacheEntry, public ::rocketspeed::djinni::SnapshotCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void Call(::rocketspeed::djinni::Status status) override;

    private:
        using ::djinni::JavaProxyCacheEntry::getGlobalRef;
        friend ::djinni::JniInterface<::rocketspeed::djinni::SnapshotCallback, ::djinni_generated::NativeSnapshotCallback>;
        friend ::djinni::JavaProxyCache<JavaProxy>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/SnapshotCallback") };
    const jmethodID method_call { ::djinni::jniGetMethodID(clazz.get(), "call", "(Lorg/rocketspeed/Status;)V") };
};

}  // namespace djinni_generated
