// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativeMsgId.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMsgId::NativeMsgId() = default;

NativeMsgId::~NativeMsgId() = default;

auto NativeMsgId::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeMsgId>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::I64::fromCpp(jniEnv, c.hi),
                                                           ::djinni::I64::fromCpp(jniEnv, c.lo))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeMsgId::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeMsgId>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_hi)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_lo))};
}

}  // namespace djinni_generated
