// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/StatusCode.hpp"

namespace djinni_generated {

class NativeStatusCode final : ::djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::StatusCode;
    using JniType = jobject;

    using Boxed = NativeStatusCode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeStatusCode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeStatusCode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeStatusCode() : JniEnum("org/rocketspeed/StatusCode") {}
    friend ::djinni::JniClass<NativeStatusCode>;
};

}  // namespace djinni_generated
