// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/MsgId.hpp"

namespace djinni_generated {

class NativeMsgId final {
public:
    using CppType = ::rocketspeed::djinni::MsgId;
    using JniType = jobject;

    using Boxed = NativeMsgId;

    ~NativeMsgId();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeMsgId();
    friend ::djinni::JniClass<NativeMsgId>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/MsgId") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JJ)V") };
    const jfieldID field_hi { ::djinni::jniGetFieldID(clazz.get(), "hi", "J") };
    const jfieldID field_lo { ::djinni::jniGetFieldID(clazz.get(), "lo", "J") };
};

}  // namespace djinni_generated
