// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/ClientImpl.hpp"

namespace djinni_generated {

class NativeClientImpl final : ::djinni::JniInterface<::rocketspeed::djinni::ClientImpl, NativeClientImpl> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::ClientImpl>;
    using JniType = jobject;

    using Boxed = NativeClientImpl;

    ~NativeClientImpl();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeClientImpl>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeClientImpl>::get()._toJava(jniEnv, c)}; }

private:
    NativeClientImpl();
    friend ::djinni::JniClass<NativeClientImpl>;
    friend ::djinni::JniInterface<::rocketspeed::djinni::ClientImpl, NativeClientImpl>;

};

}  // namespace djinni_generated
