// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativePublishCallback.hpp"  // my header
#include "Marshal.hpp"
#include "src-gen/djinni/cpp/NativeMsgId.hpp"
#include "src-gen/djinni/cpp/NativeStatus.hpp"

namespace djinni_generated {

NativePublishCallback::NativePublishCallback() : ::djinni::JniInterface<::rocketspeed::djinni::PublishCallback, NativePublishCallback>() {}

NativePublishCallback::~NativePublishCallback() = default;

NativePublishCallback::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

NativePublishCallback::JavaProxy::~JavaProxy() = default;

void NativePublishCallback::JavaProxy::Call(::rocketspeed::djinni::MsgId message_id, std::string namespace_id, std::string topic_name, int64_t seqno, ::rocketspeed::djinni::Status status) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativePublishCallback>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_call,
                           ::djinni_generated::NativeMsgId::fromCpp(jniEnv, message_id).get(),
                           ::djinni::String::fromCpp(jniEnv, namespace_id).get(),
                           ::djinni::String::fromCpp(jniEnv, topic_name).get(),
                           ::djinni::I64::fromCpp(jniEnv, seqno),
                           ::djinni_generated::NativeStatus::fromCpp(jniEnv, status).get());
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
