// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/SubscribeCallback.hpp"

namespace djinni_generated {

class NativeSubscribeCallback final : ::djinni::JniInterface<::rocketspeed::djinni::SubscribeCallback, NativeSubscribeCallback> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::SubscribeCallback>;
    using JniType = jobject;

    using Boxed = NativeSubscribeCallback;

    ~NativeSubscribeCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSubscribeCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeSubscribeCallback>::get()._toJava(jniEnv, c)}; }

private:
    NativeSubscribeCallback();
    friend ::djinni::JniClass<NativeSubscribeCallback>;
    friend ::djinni::JniInterface<::rocketspeed::djinni::SubscribeCallback, NativeSubscribeCallback>;

    class JavaProxy final : ::djinni::JavaProxyCacheEntry, public ::rocketspeed::djinni::SubscribeCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void Call(int32_t tenant_id, std::string namespace_id, std::string topic_name, int64_t start_seqno, bool subscribed, ::rocketspeed::djinni::Status status) override;

    private:
        using ::djinni::JavaProxyCacheEntry::getGlobalRef;
        friend ::djinni::JniInterface<::rocketspeed::djinni::SubscribeCallback, ::djinni_generated::NativeSubscribeCallback>;
        friend ::djinni::JavaProxyCache<JavaProxy>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("org/rocketspeed/SubscribeCallback") };
    const jmethodID method_call { ::djinni::jniGetMethodID(clazz.get(), "call", "(ILjava/lang/String;Ljava/lang/String;JZLorg/rocketspeed/Status;)V") };
};

}  // namespace djinni_generated
