// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/StorageType.hpp"

namespace djinni_generated {

class NativeStorageType final : ::djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::StorageType;
    using JniType = jobject;

    using Boxed = NativeStorageType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeStorageType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeStorageType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeStorageType() : JniEnum("org/rocketspeed/StorageType") {}
    friend ::djinni::JniClass<NativeStorageType>;
};

}  // namespace djinni_generated
