// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/NativeMessageReceivedCallback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMessageReceivedCallback::NativeMessageReceivedCallback() : ::djinni::JniInterface<::rocketspeed::djinni::MessageReceivedCallback, NativeMessageReceivedCallback>() {}

NativeMessageReceivedCallback::~NativeMessageReceivedCallback() = default;

NativeMessageReceivedCallback::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

NativeMessageReceivedCallback::JavaProxy::~JavaProxy() = default;

void NativeMessageReceivedCallback::JavaProxy::Call(int64_t sub_handle, int64_t start_seqno, std::vector<uint8_t> contents) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeMessageReceivedCallback>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_call,
                           ::djinni::I64::fromCpp(jniEnv, sub_handle),
                           ::djinni::I64::fromCpp(jniEnv, start_seqno),
                           ::djinni::Binary::fromCpp(jniEnv, contents).get());
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
