// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "src-gen/djinni/cpp/Status.hpp"

namespace rocketspeed { namespace djinni {

class SnapshotCallback {
public:
    virtual ~SnapshotCallback() {}

    virtual void Call(Status status) = 0;
};

} }  // namespace rocketspeed::djinni
