// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/SubscriptionParameters.hpp"  // my header

namespace rocketspeed { namespace djinni {


bool operator==(const SubscriptionParameters& lhs, const SubscriptionParameters& rhs) {
    return lhs.tenant_id == rhs.tenant_id &&
           lhs.namespace_id == rhs.namespace_id &&
           lhs.topic_name == rhs.topic_name &&
           lhs.start_seqno == rhs.start_seqno;
}

bool operator!=(const SubscriptionParameters& lhs, const SubscriptionParameters& rhs) {
    return !(lhs == rhs);
}

} }  // namespace rocketspeed::djinni
