// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "src-gen/djinni/cpp/Status.hpp"
#include <cstdint>
#include <string>

namespace rocketspeed { namespace djinni {

class SubscribeCallbackImpl {
public:
    virtual ~SubscribeCallbackImpl() {}

    virtual void Call(Status status, int32_t namespace_id, std::string topic_name, int64_t sequence_number, bool subscribed) = 0;
};

} }  // namespace rocketspeed::djinni
