// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "src-gen/djinni/cpp/Status.hpp"
#include <cstdint>
#include <string>

namespace rocketspeed { namespace djinni {

class SubscribeCallback {
public:
    virtual ~SubscribeCallback() {}

    virtual void Call(int32_t tenant_id, std::string namespace_id, std::string topic_name, int64_t start_seqno, bool subscribed, Status status) = 0;
};

} }  // namespace rocketspeed::djinni
