// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>

namespace rocketspeed { namespace djinni {

class WakeLockImpl {
public:
    virtual ~WakeLockImpl() {}

    virtual void Acquire(int64_t timeout) = 0;

    virtual void Release() = 0;
};

} }  // namespace rocketspeed::djinni
