// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "MsgIdImpl.hpp"  // my header

namespace rocketspeed { namespace djinni {

const int32_t MsgIdImpl::SIZE = 16;

} }  // namespace rocketspeed::djinni
