// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "NativeMsgIdImpl.hpp"  // my header
#include "HBinary.hpp"

namespace djinni_generated {

jobject NativeMsgIdImpl::toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::MsgIdImpl c) {
    djinni::LocalRef<jbyteArray> j_guid(jniEnv, ::djinni::HBinary::toJava(jniEnv, c.guid));
    const auto & data = djinni::JniClass<::djinni_generated::NativeMsgIdImpl>::get();
    jobject r = jniEnv->NewObject(data.clazz.get(), data.jconstructor, j_guid.get());
    djinni::jniExceptionCheck(jniEnv);
    return r;
}

::rocketspeed::djinni::MsgIdImpl NativeMsgIdImpl::fromJava(JNIEnv* jniEnv, jobject j) {
    assert(j != nullptr);
    const auto & data = djinni::JniClass<::djinni_generated::NativeMsgIdImpl>::get();
    return ::rocketspeed::djinni::MsgIdImpl(
        ::djinni::HBinary::fromJava(jniEnv, djinni::LocalRef<jbyteArray>(jniEnv, static_cast<jbyteArray>(jniEnv->GetObjectField(j, data.field_guid))).get()));
}

}  // namespace djinni_generated
