// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "NativeStatus.hpp"  // my header
#include "HString.hpp"
#include "NativeStatusCode.hpp"

namespace djinni_generated {

jobject NativeStatus::toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::Status c) {
    djinni::LocalRef<jobject> j_code(jniEnv, NativeStatusCode::toJava(jniEnv, c.code));
    djinni::LocalRef<jstring> j_state(jniEnv, ::djinni::HString::toJava(jniEnv, c.state));
    const auto & data = djinni::JniClass<::djinni_generated::NativeStatus>::get();
    jobject r = jniEnv->NewObject(data.clazz.get(), data.jconstructor, j_code.get(), j_state.get());
    djinni::jniExceptionCheck(jniEnv);
    return r;
}

::rocketspeed::djinni::Status NativeStatus::fromJava(JNIEnv* jniEnv, jobject j) {
    assert(j != nullptr);
    const auto & data = djinni::JniClass<::djinni_generated::NativeStatus>::get();
    return ::rocketspeed::djinni::Status(
        NativeStatusCode::fromJava(jniEnv, djinni::LocalRef<jobject>(jniEnv, jniEnv->GetObjectField(j, data.field_code)).get()),
        ::djinni::HString::fromJava(jniEnv, djinni::LocalRef<jstring>(jniEnv, static_cast<jstring>(jniEnv->GetObjectField(j, data.field_state))).get()));
}

}  // namespace djinni_generated
