// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "NativeHostId.hpp"  // my header
#include "HI32.hpp"
#include "HString.hpp"

namespace djinni_generated {

jobject NativeHostId::toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::HostId c) {
    djinni::LocalRef<jstring> j_hostname(jniEnv, ::djinni::HString::toJava(jniEnv, c.hostname));
    jint j_port = ::djinni::HI32::Unboxed::toJava(jniEnv, c.port);
    const auto & data = djinni::JniClass<::djinni_generated::NativeHostId>::get();
    jobject r = jniEnv->NewObject(data.clazz.get(), data.jconstructor, j_hostname.get(), j_port);
    djinni::jniExceptionCheck(jniEnv);
    return r;
}

::rocketspeed::djinni::HostId NativeHostId::fromJava(JNIEnv* jniEnv, jobject j) {
    assert(j != nullptr);
    const auto & data = djinni::JniClass<::djinni_generated::NativeHostId>::get();
    return ::rocketspeed::djinni::HostId(
        ::djinni::HString::fromJava(jniEnv, djinni::LocalRef<jstring>(jniEnv, static_cast<jstring>(jniEnv->GetObjectField(j, data.field_hostname))).get()),
        ::djinni::HI32::Unboxed::fromJava(jniEnv, jniEnv->GetIntField(j, data.field_port)));
}

}  // namespace djinni_generated
