// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "SubscriptionStorage.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSubscriptionStorage final {
public:
    using CppType = ::rocketspeed::djinni::SubscriptionStorage;
    using JniType = jobject;

    static jobject toJava(JNIEnv*, ::rocketspeed::djinni::SubscriptionStorage);
    static ::rocketspeed::djinni::SubscriptionStorage fromJava(JNIEnv*, jobject);

    const djinni::GlobalRef<jclass> clazz { djinni::jniFindClass("org/rocketspeed/SubscriptionStorage") };
    const jmethodID jconstructor { djinni::jniGetMethodID(clazz.get(), "<init>", "(Lorg/rocketspeed/StorageType;Ljava/lang/String;)V") };
    const jfieldID field_type { djinni::jniGetFieldID(clazz.get(), "type", "Lorg/rocketspeed/StorageType;") };
    const jfieldID field_filePath { djinni::jniGetFieldID(clazz.get(), "filePath", "Ljava/lang/String;") };

private:
    NativeSubscriptionStorage() {}
    friend class djinni::JniClass<::djinni_generated::NativeSubscriptionStorage>;
};

}  // namespace djinni_generated
