// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "StorageType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeStorageType final : djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::StorageType;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::StorageType c) { return djinni::JniClass<NativeStorageType>::get().create(jniEnv, static_cast<int>(c)).release(); }
    static ::rocketspeed::djinni::StorageType fromJava(JNIEnv* jniEnv, jobject j) { return static_cast<::rocketspeed::djinni::StorageType>(djinni::JniClass<NativeStorageType>::get().ordinal(jniEnv, j)); }

private:
    NativeStorageType() : JniEnum("org/rocketspeed/StorageType") {}
    friend class djinni::JniClass<NativeStorageType>;
};

}  // namespace djinni_generated
