// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "SubscriptionStartImpl.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSubscriptionStartImpl final {
public:
    using CppType = ::rocketspeed::djinni::SubscriptionStartImpl;
    using JniType = jobject;

    static jobject toJava(JNIEnv*, ::rocketspeed::djinni::SubscriptionStartImpl);
    static ::rocketspeed::djinni::SubscriptionStartImpl fromJava(JNIEnv*, jobject);

    const djinni::GlobalRef<jclass> clazz { djinni::jniFindClass("org/rocketspeed/SubscriptionStartImpl") };
    const jmethodID jconstructor { djinni::jniGetMethodID(clazz.get(), "<init>", "(JZ)V") };
    const jfieldID field_sequenceNumber { djinni::jniGetFieldID(clazz.get(), "sequenceNumber", "J") };
    const jfieldID field_present { djinni::jniGetFieldID(clazz.get(), "present", "Z") };

private:
    NativeSubscriptionStartImpl() {}
    friend class djinni::JniClass<::djinni_generated::NativeSubscriptionStartImpl>;
};

}  // namespace djinni_generated
