// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "MsgIdImpl.hpp"
#include "Status.hpp"
#include <cstdint>
#include <string>
#include <vector>

namespace rocketspeed { namespace djinni {

class PublishCallbackImpl {
public:
    virtual ~PublishCallbackImpl() {}

    virtual void Call(const Status & status, int16_t namespace_id, const std::string & topic_name, const MsgIdImpl & message_id, int64_t sequence_number, const std::vector<uint8_t> & contents) = 0;
};

} }  // namespace rocketspeed::djinni
