// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace rocketspeed { namespace djinni {

struct SubscriptionStartImpl final {

    int64_t sequence_number;

    bool present;


    SubscriptionStartImpl(
            int64_t sequence_number,
            bool present) :
                sequence_number(std::move(sequence_number)),
                present(std::move(present)) {
    }
};

} }  // namespace rocketspeed::djinni
