// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ClientImpl {
    public abstract PublishStatus Publish0(short namespaceId, String topicName, RetentionBase retention, byte[] data);

    /** TODO(stupaq) the message_id param should be optional */
    public abstract PublishStatus Publish1(short namespaceId, String topicName, RetentionBase retention, byte[] data, MsgIdImpl messageId);

    public abstract void ListenTopics(ArrayList<SubscriptionRequestImpl> names);

    public abstract void Acknowledge(short namespaceId, String topicName, long sequenceNumber, byte[] contents);

    public abstract void Close();

    public static native ClientImpl Open(ConfigurationImpl config, String clientId, PublishCallbackImpl publishCallback, SubscribeCallbackImpl subscribeCallback, ReceiveCallbackImpl receiveCallback, SubscriptionStorage storage);

    public static final class CppProxy extends ClientImpl
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public PublishStatus Publish0(short namespaceId, String topicName, RetentionBase retention, byte[] data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_Publish0(this.nativeRef, namespaceId, topicName, retention, data);
        }
        private native PublishStatus native_Publish0(long _nativeRef, short namespaceId, String topicName, RetentionBase retention, byte[] data);

        @Override
        public PublishStatus Publish1(short namespaceId, String topicName, RetentionBase retention, byte[] data, MsgIdImpl messageId)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_Publish1(this.nativeRef, namespaceId, topicName, retention, data, messageId);
        }
        private native PublishStatus native_Publish1(long _nativeRef, short namespaceId, String topicName, RetentionBase retention, byte[] data, MsgIdImpl messageId);

        @Override
        public void ListenTopics(ArrayList<SubscriptionRequestImpl> names)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_ListenTopics(this.nativeRef, names);
        }
        private native void native_ListenTopics(long _nativeRef, ArrayList<SubscriptionRequestImpl> names);

        @Override
        public void Acknowledge(short namespaceId, String topicName, long sequenceNumber, byte[] contents)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_Acknowledge(this.nativeRef, namespaceId, topicName, sequenceNumber, contents);
        }
        private native void native_Acknowledge(long _nativeRef, short namespaceId, String topicName, long sequenceNumber, byte[] contents);

        @Override
        public void Close()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_Close(this.nativeRef);
        }
        private native void native_Close(long _nativeRef);
    }
}
