// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class MsgIdImpl {

    public static final int SIZE = 16;


    /*package*/ final byte[] guid;

    public MsgIdImpl(
            byte[] guid) {
        this.guid = guid;
    }

    public byte[] getGuid() {
        return guid;
    }
}
