// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public enum StatusCode {
    OK,
    NOTFOUND,
    NOTSUPPORTED,
    INVALIDARGUMENT,
    IOERROR,
    NOTINITIALIZED,
    INTERNAL,
    UNAUTHORIZED,
    TIMEDOUT,
    ;
}
