// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class SubscriptionRequestImpl {


    /*package*/ final short namespaceId;

    /*package*/ final String topicName;

    /*package*/ final boolean subscribe;

    /*package*/ final SubscriptionStartImpl sequenceNumber;

    public SubscriptionRequestImpl(
            short namespaceId,
            String topicName,
            boolean subscribe,
            SubscriptionStartImpl sequenceNumber) {
        this.namespaceId = namespaceId;
        this.topicName = topicName;
        this.subscribe = subscribe;
        this.sequenceNumber = sequenceNumber;
    }

    public short getNamespaceId() {
        return namespaceId;
    }

    public String getTopicName() {
        return topicName;
    }

    public boolean getSubscribe() {
        return subscribe;
    }

    public SubscriptionStartImpl getSequenceNumber() {
        return sequenceNumber;
    }
}
