// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class SubscriptionStartImpl {


    /*package*/ final long sequenceNumber;

    /*package*/ final boolean present;

    public SubscriptionStartImpl(
            long sequenceNumber,
            boolean present) {
        this.sequenceNumber = sequenceNumber;
        this.present = present;
    }

    public long getSequenceNumber() {
        return sequenceNumber;
    }

    public boolean getPresent() {
        return present;
    }
}
