// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class SubscriptionStorage {


    /*package*/ final StorageType type;

    /*package*/ final String filePath;

    public SubscriptionStorage(
            StorageType type,
            String filePath) {
        this.type = type;
        this.filePath = filePath;
    }

    public StorageType getType() {
        return type;
    }

    /**
     * Used only when this is a file storage
     * TODO(stupaq) this should be optional
     */
    public String getFilePath() {
        return filePath;
    }
}
