// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/ClientImpl.hpp"

namespace djinni_generated {

class NativeClientImpl final : djinni::JniInterface<::rocketspeed::djinni::ClientImpl, NativeClientImpl> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::ClientImpl>;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, std::shared_ptr<::rocketspeed::djinni::ClientImpl> c) { return djinni::JniClass<::djinni_generated::NativeClientImpl>::get()._toJava(jniEnv, c); }
    static std::shared_ptr<::rocketspeed::djinni::ClientImpl> fromJava(JNIEnv* jniEnv, jobject j) { return djinni::JniClass<::djinni_generated::NativeClientImpl>::get()._fromJava(jniEnv, j); }


private:
    NativeClientImpl();
    friend class djinni::JniClass<::djinni_generated::NativeClientImpl>;
};

}  // namespace djinni_generated
