// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/RetentionBase.hpp"

namespace djinni_generated {

class NativeRetentionBase final : djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::RetentionBase;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::RetentionBase c) { return djinni::JniClass<NativeRetentionBase>::get().create(jniEnv, static_cast<int>(c)).release(); }
    static ::rocketspeed::djinni::RetentionBase fromJava(JNIEnv* jniEnv, jobject j) { return static_cast<::rocketspeed::djinni::RetentionBase>(djinni::JniClass<NativeRetentionBase>::get().ordinal(jniEnv, j)); }

private:
    NativeRetentionBase() : JniEnum("org/rocketspeed/RetentionBase") {}
    friend class djinni::JniClass<NativeRetentionBase>;
};

}  // namespace djinni_generated
