// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/jni/NativeDisconnectCallback.hpp"  // my header
#include "HList.hpp"
#include "HString.hpp"

namespace djinni_generated {

NativeDisconnectCallback::NativeDisconnectCallback() : djinni::JniInterface<::rocketspeed::djinni::DisconnectCallback, NativeDisconnectCallback>() {}

NativeDisconnectCallback::JavaProxy::JavaProxy(jobject obj) : JavaProxyCacheEntry(obj) {}

void NativeDisconnectCallback::JavaProxy::JavaProxy::Call(std::vector<std::string> c_client_ids) {
    JNIEnv * const jniEnv = djinni::jniGetThreadEnv();
    djinni::JniLocalScope jscope(jniEnv, 10);
    djinni::LocalRef<jobject> j_client_ids(jniEnv, ::djinni::HList<::djinni::HString>::toJava(jniEnv, c_client_ids));
    const auto & data = djinni::JniClass<::djinni_generated::NativeDisconnectCallback>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_call, j_client_ids.get());
    djinni::jniExceptionCheck(jniEnv);
};

}  // namespace djinni_generated
