// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/jni/NativeWakeLockImpl.hpp"  // my header
#include "HI64.hpp"

namespace djinni_generated {

NativeWakeLockImpl::NativeWakeLockImpl() : djinni::JniInterface<::rocketspeed::djinni::WakeLockImpl, NativeWakeLockImpl>() {}

NativeWakeLockImpl::JavaProxy::JavaProxy(jobject obj) : JavaProxyCacheEntry(obj) {}

void NativeWakeLockImpl::JavaProxy::JavaProxy::Acquire(int64_t c_timeout) {
    JNIEnv * const jniEnv = djinni::jniGetThreadEnv();
    djinni::JniLocalScope jscope(jniEnv, 10);
    jlong j_timeout = ::djinni::HI64::Unboxed::toJava(jniEnv, c_timeout);
    const auto & data = djinni::JniClass<::djinni_generated::NativeWakeLockImpl>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_Acquire, j_timeout);
    djinni::jniExceptionCheck(jniEnv);
};

void NativeWakeLockImpl::JavaProxy::JavaProxy::Release() {
    JNIEnv * const jniEnv = djinni::jniGetThreadEnv();
    djinni::JniLocalScope jscope(jniEnv, 10);
    const auto & data = djinni::JniClass<::djinni_generated::NativeWakeLockImpl>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_Release);
    djinni::jniExceptionCheck(jniEnv);
};

}  // namespace djinni_generated
