// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "src-gen/djinni/cpp/jni/NativeSnapshotCallbackImpl.hpp"  // my header
#include "src-gen/djinni/cpp/jni/NativeStatus.hpp"

namespace djinni_generated {

NativeSnapshotCallbackImpl::NativeSnapshotCallbackImpl() : djinni::JniInterface<::rocketspeed::djinni::SnapshotCallbackImpl, NativeSnapshotCallbackImpl>() {}

NativeSnapshotCallbackImpl::JavaProxy::JavaProxy(jobject obj) : JavaProxyCacheEntry(obj) {}

void NativeSnapshotCallbackImpl::JavaProxy::JavaProxy::Call(::rocketspeed::djinni::Status c_status) {
    JNIEnv * const jniEnv = djinni::jniGetThreadEnv();
    djinni::JniLocalScope jscope(jniEnv, 10);
    djinni::LocalRef<jobject> j_status(jniEnv, NativeStatus::toJava(jniEnv, c_status));
    const auto & data = djinni::JniClass<::djinni_generated::NativeSnapshotCallbackImpl>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_Call, j_status.get());
    djinni::jniExceptionCheck(jniEnv);
};

}  // namespace djinni_generated
