// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/ProxyImpl.hpp"

namespace djinni_generated {

class NativeProxyImpl final : djinni::JniInterface<::rocketspeed::djinni::ProxyImpl, NativeProxyImpl> {
public:
    using CppType = std::shared_ptr<::rocketspeed::djinni::ProxyImpl>;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, std::shared_ptr<::rocketspeed::djinni::ProxyImpl> c) { return djinni::JniClass<::djinni_generated::NativeProxyImpl>::get()._toJava(jniEnv, c); }
    static std::shared_ptr<::rocketspeed::djinni::ProxyImpl> fromJava(JNIEnv* jniEnv, jobject j) { return djinni::JniClass<::djinni_generated::NativeProxyImpl>::get()._fromJava(jniEnv, j); }


private:
    NativeProxyImpl();
    friend class djinni::JniClass<::djinni_generated::NativeProxyImpl>;
};

}  // namespace djinni_generated
