// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/LogLevel.hpp"

namespace djinni_generated {

class NativeLogLevel final : djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::LogLevel;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::LogLevel c) { return djinni::JniClass<NativeLogLevel>::get().create(jniEnv, static_cast<int>(c)).release(); }
    static ::rocketspeed::djinni::LogLevel fromJava(JNIEnv* jniEnv, jobject j) { return static_cast<::rocketspeed::djinni::LogLevel>(djinni::JniClass<NativeLogLevel>::get().ordinal(jniEnv, j)); }

private:
    NativeLogLevel() : JniEnum("org/rocketspeed/LogLevel") {}
    friend class djinni::JniClass<NativeLogLevel>;
};

}  // namespace djinni_generated
