// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/ConfigurationImpl.hpp"

namespace djinni_generated {

class NativeConfigurationImpl final {
public:
    using CppType = ::rocketspeed::djinni::ConfigurationImpl;
    using JniType = jobject;

    static jobject toJava(JNIEnv*, ::rocketspeed::djinni::ConfigurationImpl);
    static ::rocketspeed::djinni::ConfigurationImpl fromJava(JNIEnv*, jobject);

    const djinni::GlobalRef<jclass> clazz { djinni::jniFindClass("org/rocketspeed/ConfigurationImpl") };
    const jmethodID jconstructor { djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;Ljava/util/ArrayList;)V") };
    const jfieldID field_pilots { djinni::jniGetFieldID(clazz.get(), "pilots", "Ljava/util/ArrayList;") };
    const jfieldID field_copilots { djinni::jniGetFieldID(clazz.get(), "copilots", "Ljava/util/ArrayList;") };

private:
    NativeConfigurationImpl() {}
    friend class djinni::JniClass<::djinni_generated::NativeConfigurationImpl>;
};

}  // namespace djinni_generated
