// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/PublishStatus.hpp"

namespace djinni_generated {

class NativePublishStatus final {
public:
    using CppType = ::rocketspeed::djinni::PublishStatus;
    using JniType = jobject;

    static jobject toJava(JNIEnv*, ::rocketspeed::djinni::PublishStatus);
    static ::rocketspeed::djinni::PublishStatus fromJava(JNIEnv*, jobject);

    const djinni::GlobalRef<jclass> clazz { djinni::jniFindClass("org/rocketspeed/PublishStatus") };
    const jmethodID jconstructor { djinni::jniGetMethodID(clazz.get(), "<init>", "(Lorg/rocketspeed/Status;Lorg/rocketspeed/MsgIdImpl;)V") };
    const jfieldID field_status { djinni::jniGetFieldID(clazz.get(), "status", "Lorg/rocketspeed/Status;") };
    const jfieldID field_messageId { djinni::jniGetFieldID(clazz.get(), "messageId", "Lorg/rocketspeed/MsgIdImpl;") };

private:
    NativePublishStatus() {}
    friend class djinni::JniClass<::djinni_generated::NativePublishStatus>;
};

}  // namespace djinni_generated
