// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#pragma once

#include "djinni_support.hpp"
#include "src-gen/djinni/cpp/StatusCode.hpp"

namespace djinni_generated {

class NativeStatusCode final : djinni::JniEnum {
public:
    using CppType = ::rocketspeed::djinni::StatusCode;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::StatusCode c) { return djinni::JniClass<NativeStatusCode>::get().create(jniEnv, static_cast<int>(c)).release(); }
    static ::rocketspeed::djinni::StatusCode fromJava(JNIEnv* jniEnv, jobject j) { return static_cast<::rocketspeed::djinni::StatusCode>(djinni::JniClass<NativeStatusCode>::get().ordinal(jniEnv, j)); }

private:
    NativeStatusCode() : JniEnum("org/rocketspeed/StatusCode") {}
    friend class djinni::JniClass<NativeStatusCode>;
};

}  // namespace djinni_generated
