// Copyright (c) 2014, Facebook, Inc.  All rights reserved.
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree. An additional grant
// of patent rights can be found in the PATENTS file in the same directory.
#pragma once

#include "include/Env.h"
#include "include/Types.h"

namespace rocketspeed {

struct ControlTowerOptions {
  //
  // Use the specified object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  // Default: Env::Default()
  Env* env;

  // The configuration of this rocketspeed instance
  // Default: TODO(dhruba) 1234
  Configuration* conf;

  // Any internal progress/error information generated by the daemon
  // is written to info_log if it is non-nullptr, or to a file stored
  // in the working directory of the daemon if info_log is nullptr.
  // Default: nullptr
  std::shared_ptr<Logger> info_log;

  // Logging level of server logs
  // Default: INFO_LEVEL
  InfoLogLevel info_log_level;

  // Create ControlTowerOptions with default values for all fields
  ControlTowerOptions();
};

}  // namespace rocketspeed
