// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

import java.util.ArrayList;

public abstract class DisconnectCallback {
    public abstract void call(ArrayList<Long> sessionIds);
}
