// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class HostId {


    /*package*/ final String host;

    /*package*/ final int port;

    public HostId(
            String host,
            int port) {
        this.host = host;
        this.port = port;
    }

    public String getHost() {
        return host;
    }

    public int getPort() {
        return port;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof HostId)) {
            return false;
        }
        HostId other = (HostId) obj;
        return this.host.equals(other.host) &&
                this.port == other.port;
    }
}
