// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class MessageCallback {
    public abstract void call(String clientId, byte[] message);
}
