// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class MessageReceivedCallback {
    public abstract void call(long subHandle, long startSeqno, byte[] contents);
}
