// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public class MsgIdBase {


    /*package*/ final long hi;

    /*package*/ final long lo;

    public MsgIdBase(
            long hi,
            long lo) {
        this.hi = hi;
        this.lo = lo;
    }

    public long getHi() {
        return hi;
    }

    public long getLo() {
        return lo;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof MsgIdBase)) {
            return false;
        }
        MsgIdBase other = (MsgIdBase) obj;
        return this.hi == other.hi &&
                this.lo == other.lo;
    }
}
