// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class PublishStatus {


    /*package*/ final Status status;

    /*package*/ final MsgIdImpl messageId;

    public PublishStatus(
            Status status,
            MsgIdImpl messageId) {
        this.status = status;
        this.messageId = messageId;
    }

    public Status getStatus() {
        return status;
    }

    public MsgIdImpl getMessageId() {
        return messageId;
    }
}
