// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class PublishCallbackImpl {
    public abstract void Call(Status status, int namespaceId, String topicName, MsgIdImpl messageId, long sequenceNumber);
}
