// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class PublishCallback {
    public abstract void call(MsgId messageId, String namespaceId, String topicName, long seqno, Status status);
}
