// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class ReceiveCallbackImpl {
    public abstract void Call(int namespaceId, String topicName, long sequenceNumber, byte[] contents);
}
