// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class Rocketeer {
    public abstract void handleNewSubscription(InboundID inboundId, SubscriptionParameters params);

    public abstract void handleTermination(InboundID inboundId, boolean fromClient);
}
