// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class SnapshotCallbackImpl {
    public abstract void Call(Status status);
}
