// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public class StatusBase {


    /*package*/ final StatusCode code;

    /*package*/ final String state;

    public StatusBase(
            StatusCode code,
            String state) {
        this.code = code;
        this.state = state;
    }

    public StatusCode getCode() {
        return code;
    }

    public String getState() {
        return state;
    }
}
