// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class SubscribeCallback {
    public abstract void call(int tenantId, String namespaceId, String topicName, long startSeqno, boolean subscribed, Status status);
}
