// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class SubscriptionParameters {


    /*package*/ final int tenantId;

    /*package*/ final String namespaceId;

    /*package*/ final String topicName;

    /*package*/ final long startSeqno;

    public SubscriptionParameters(
            int tenantId,
            String namespaceId,
            String topicName,
            long startSeqno) {
        this.tenantId = tenantId;
        this.namespaceId = namespaceId;
        this.topicName = topicName;
        this.startSeqno = startSeqno;
    }

    public int getTenantId() {
        return tenantId;
    }

    public String getNamespaceId() {
        return namespaceId;
    }

    public String getTopicName() {
        return topicName;
    }

    public long getStartSeqno() {
        return startSeqno;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SubscriptionParameters)) {
            return false;
        }
        SubscriptionParameters other = (SubscriptionParameters) obj;
        return this.tenantId == other.tenantId &&
                this.namespaceId.equals(other.namespaceId) &&
                this.topicName.equals(other.topicName) &&
                this.startSeqno == other.startSeqno;
    }
}
