// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public final class SubscriptionRequestImpl {


    /*package*/ final int namespaceId;

    /*package*/ final String topicName;

    /*package*/ final boolean subscribe;

    /*package*/ final Long start;

    public SubscriptionRequestImpl(
            int namespaceId,
            String topicName,
            boolean subscribe,
            Long start) {
        this.namespaceId = namespaceId;
        this.topicName = topicName;
        this.subscribe = subscribe;
        this.start = start;
    }

    public int getNamespaceId() {
        return namespaceId;
    }

    public String getTopicName() {
        return topicName;
    }

    public boolean getSubscribe() {
        return subscribe;
    }

    public Long getStart() {
        return start;
    }
}
