// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class SubscribeCallbackImpl {
    public abstract void Call(Status status, String namespaceId, String topicName, long sequenceNumber, boolean subscribed);
}
