// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

package org.rocketspeed;

public abstract class WakeLockImpl {
    public abstract void Acquire(long timeout);

    public abstract void Release();
}
