// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "NativeConfigurationImpl.hpp"  // my header
#include "HI16.hpp"
#include "HList.hpp"
#include "NativeHostId.hpp"

namespace djinni_generated {

jobject NativeConfigurationImpl::toJava(JNIEnv* jniEnv, ::rocketspeed::djinni::ConfigurationImpl c) {
    djinni::LocalRef<jobject> j_pilots(jniEnv, ::djinni::HList<NativeHostId>::toJava(jniEnv, c.pilots));
    djinni::LocalRef<jobject> j_copilots(jniEnv, ::djinni::HList<NativeHostId>::toJava(jniEnv, c.copilots));
    jshort j_tenant_id = ::djinni::HI16::Unboxed::toJava(jniEnv, c.tenant_id);
    const auto & data = djinni::JniClass<::djinni_generated::NativeConfigurationImpl>::get();
    jobject r = jniEnv->NewObject(data.clazz.get(), data.jconstructor, j_pilots.get(), j_copilots.get(), j_tenant_id);
    djinni::jniExceptionCheck(jniEnv);
    return r;
}

::rocketspeed::djinni::ConfigurationImpl NativeConfigurationImpl::fromJava(JNIEnv* jniEnv, jobject j) {
    assert(j != nullptr);
    const auto & data = djinni::JniClass<::djinni_generated::NativeConfigurationImpl>::get();
    return ::rocketspeed::djinni::ConfigurationImpl(
        ::djinni::HList<NativeHostId>::fromJava(jniEnv, djinni::LocalRef<jobject>(jniEnv, jniEnv->GetObjectField(j, data.field_pilots)).get()),
        ::djinni::HList<NativeHostId>::fromJava(jniEnv, djinni::LocalRef<jobject>(jniEnv, jniEnv->GetObjectField(j, data.field_copilots)).get()),
        ::djinni::HI16::Unboxed::fromJava(jniEnv, jniEnv->GetShortField(j, data.field_tenantId)));
}

}  // namespace djinni_generated
