// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from rocketspeed.djinni

#include "NativePublishCallbackImpl.hpp"  // my header
#include "HBinary.hpp"
#include "HI16.hpp"
#include "HI64.hpp"
#include "HString.hpp"
#include "NativeMsgIdImpl.hpp"
#include "NativeStatus.hpp"

namespace djinni_generated {

NativePublishCallbackImpl::NativePublishCallbackImpl() : djinni::JniInterface<::rocketspeed::djinni::PublishCallbackImpl, NativePublishCallbackImpl>() {}

NativePublishCallbackImpl::JavaProxy::JavaProxy(jobject obj) : JavaProxyCacheEntry(obj) {}

void NativePublishCallbackImpl::JavaProxy::JavaProxy::Call(::rocketspeed::djinni::Status c_status, int16_t c_namespace_id, std::string c_topic_name, ::rocketspeed::djinni::MsgIdImpl c_message_id, int64_t c_sequence_number, std::vector<uint8_t> c_contents) {
    JNIEnv * const jniEnv = djinni::jniGetThreadEnv();
    djinni::JniLocalScope jscope(jniEnv, 10);
    djinni::LocalRef<jobject> j_status(jniEnv, NativeStatus::toJava(jniEnv, c_status));
    jshort j_namespace_id = ::djinni::HI16::Unboxed::toJava(jniEnv, c_namespace_id);
    djinni::LocalRef<jstring> j_topic_name(jniEnv, ::djinni::HString::toJava(jniEnv, c_topic_name));
    djinni::LocalRef<jobject> j_message_id(jniEnv, NativeMsgIdImpl::toJava(jniEnv, c_message_id));
    jlong j_sequence_number = ::djinni::HI64::Unboxed::toJava(jniEnv, c_sequence_number);
    djinni::LocalRef<jbyteArray> j_contents(jniEnv, ::djinni::HBinary::toJava(jniEnv, c_contents));
    const auto & data = djinni::JniClass<::djinni_generated::NativePublishCallbackImpl>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_Call, j_status.get(), j_namespace_id, j_topic_name.get(), j_message_id.get(), j_sequence_number, j_contents.get());
    djinni::jniExceptionCheck(jniEnv);
};

}  // namespace djinni_generated
